DELETE FROM cand_thor
WHERE "PX_ID" NOT IN (SELECT "PX_ID" FROM tx_hr);

ALTER TABLE cand_thor
ADD CONSTRAINT foreign_key_cand_thor
FOREIGN KEY ("PX_ID") REFERENCES tx_hr("PX_ID");

DELETE FROM donor_deceased
WHERE "DONOR_ID" NOT IN (SELECT "DONOR_ID" FROM tx_hr);

ALTER TABLE donor_deceased
ADD CONSTRAINT foreign_key_donor_deceased
FOREIGN KEY ("DONOR_ID") REFERENCES tx_hr("DONOR_ID");

DELETE FROM donor_disposition
WHERE "DONOR_ID" NOT IN (SELECT "DONOR_ID" FROM tx_hr);

ALTER TABLE donor_disposition
ADD CONSTRAINT foreign_key_donor_disposition
FOREIGN KEY ("DONOR_ID") REFERENCES tx_hr("DONOR_ID");

DELETE FROM immuno
WHERE "TRR_ID" NOT IN (SELECT "TRR_ID" FROM tx_hr);

ALTER TABLE immuno
ADD CONSTRAINT foreign_key_immuno
FOREIGN KEY ("TRR_ID") REFERENCES tx_hr("TRR_ID");

DELETE FROM ptr_hr_20210101_20211231_pub
WHERE "DONOR_ID" NOT IN (SELECT "DONOR_ID" FROM tx_hr);

ALTER TABLE ptr_hr_20210101_20211231_pub
ADD CONSTRAINT foreign_key_ptr2021
FOREIGN KEY ("DONOR_ID") REFERENCES tx_hr("DONOR_ID");

DELETE FROM ptr_hr_20220101_20221231_pub
WHERE "DONOR_ID" NOT IN (SELECT "DONOR_ID" FROM tx_hr);

ALTER TABLE ptr_hr_20220101_20221231_pub
ADD CONSTRAINT foreign_key_ptr2022
FOREIGN KEY ("DONOR_ID") REFERENCES tx_hr("DONOR_ID");

DELETE FROM ptr_hr_20230101_20231231_pub
WHERE "DONOR_ID" NOT IN (SELECT "DONOR_ID" FROM tx_hr);

ALTER TABLE ptr_hr_20230101_20231231_pub
ADD CONSTRAINT foreign_key_ptr2023
FOREIGN KEY ("DONOR_ID") REFERENCES tx_hr("DONOR_ID");

DELETE FROM rec_histo
WHERE "REC_HISTO_TX_ID" NOT IN (SELECT "REC_HISTO_TX_ID" FROM tx_hr);

ALTER TABLE rec_histo
ADD CONSTRAINT foreign_key_histo
FOREIGN KEY ("REC_HISTO_TX_ID") REFERENCES tx_hr("REC_HISTO_TX_ID");

DELETE FROM rec_histo_xmat
WHERE "REC_HISTO_TX_ID" NOT IN (SELECT "REC_HISTO_TX_ID" FROM tx_hr);

ALTER TABLE rec_histo_xmat
ADD CONSTRAINT foreign_key_histo_xmat
FOREIGN KEY ("REC_HISTO_TX_ID") REFERENCES tx_hr("REC_HISTO_TX_ID");

DELETE FROM stathist_thor
WHERE "PX_ID" NOT IN (SELECT "PX_ID" FROM tx_hr);

ALTER TABLE stathist_thor
ADD CONSTRAINT foreign_key_hist_thor
FOREIGN KEY ("PX_ID") REFERENCES tx_hr("PX_ID");

DELETE FROM statjust_hr1a
WHERE "PX_ID" NOT IN (SELECT "PX_ID" FROM tx_hr);

ALTER TABLE statjust_hr1a
ADD CONSTRAINT foreign_key_hr1a
FOREIGN KEY ("PX_ID") REFERENCES tx_hr("PX_ID");

DELETE FROM statjust_hr1b
WHERE "PX_ID" NOT IN (SELECT "PX_ID" FROM tx_hr);

ALTER TABLE statjust_hr1b
ADD CONSTRAINT foreign_key_hr1b
FOREIGN KEY ("PX_ID") REFERENCES tx_hr("PX_ID");





